name: stockmap_mr
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  go_router: ^15.1.2
  equatable: ^2.0.5
  intl: ^0.19.0
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  freezed: ^3.0.6
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/maponus-logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/maponus-logo.jpg"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/maponus-logo.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/maponus-logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
